CREATE TABLE users (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  email VARCHAR(255) NOT NULL UNIQUE,
  pass VARCHAR(255) NOT NULL
) ENGINE = INNODB;
CREATE TABLE pictures (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  path VARCHAR(255) NOT NULL,
  description TEXT NULL,
  user_id INT NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id)
) ENGINE = INNODB;
CREATE TABLE tags (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL UNIQUE
) ENGINE = INNODB;
CREATE TABLE pictures_tags (
  picture_id INT NOT NULL,
  tag_id INT NOT NULL,
  date_created DATETIME NOT NULL,
  FOREIGN KEY (picture_id) REFERENCES pictures(id),
  FOREIGN KEY (tag_id) REFERENCES tags(id),
  PRIMARY KEY (picture_id, tag_id)
) ENGINE = INNODB;